# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BytehouseCli < Formula
  desc "ByteHouse SQL Gateway Command-Line Interface"
  homepage "https://github.com/bytehouse-cloud/cli"
  version "1.26.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.26.5/bytehouse-cli_1.26.5_macOS_arm64.tar.gz"
      sha256 "827425ddfc613fcd628fe19a681eefedbeaf282a36a5f65d633cc692db4708d4"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.26.5/bytehouse-cli_1.26.5_macOS_x86_64.tar.gz"
      sha256 "bbe232ff567d335e1f21974e9ce34418bfd005925ed12df43ebee9da6408c216"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.26.5/bytehouse-cli_1.26.5_Linux_x86_64.tar.gz"
      sha256 "6f80c4d9b1ed55e45f53f753715bbbc716d84cc212fb989477596855474caed9"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
  end

  def caveats; <<~EOS
    Bytehouse SQL Gateway Command Line Interface to interact with cnch via gateway
  EOS
  end

  test do
    system "#{bin}/bytehouse-cli", "--version"
  end
end
