# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BytehouseCli < Formula
  desc "ByteHouse SQL Gateway Command-Line Interface"
  homepage "https://github.com/bytehouse-cloud/cli"
  version "1.5.27"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.5.27/bytehouse-cli_1.5.27_macOS_x86_64.tar.gz"
      sha256 "688e9d0de095415fb9b1643196e9c13445fdf1a4767d644f9804ed01f88117cd"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.5.27/bytehouse-cli_1.5.27_macOS_arm64.tar.gz"
      sha256 "9a54f4b338c9dcd4db75b6b595d7e6a0ec19a7e3f943ad183c5336b1f28ba8e0"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.5.27/bytehouse-cli_1.5.27_Linux_x86_64.tar.gz"
      sha256 "4518a166bda3e31f5ed26a67c48bbd61118033148d84639c0b22543ff4aa3ba0"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
  end

  def caveats; <<~EOS
    Bytehouse SQL Gateway Command Line Interface to interact with cnch via gateway
  EOS
  end

  test do
    system "#{bin}/bytehouse-cli", "--version"
  end
end
