# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BytehouseCli < Formula
  desc "ByteHouse SQL Gateway Command-Line Interface"
  homepage "https://github.com/bytehouse-cloud/cli"
  version "1.16.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.16.2/bytehouse-cli_1.16.2_macOS_arm64.tar.gz"
      sha256 "fd82e26afa4b1507da7849628e6e890fd4cf37c9ad223e934b8aa5191f2ffbb6"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.16.2/bytehouse-cli_1.16.2_macOS_x86_64.tar.gz"
      sha256 "0c95254f88ef2bb3a525335b8debbca26d221ad3abff10ea5f9b76b07ed19d0f"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bytehouse-cloud/cli/releases/download/v1.16.2/bytehouse-cli_1.16.2_Linux_x86_64.tar.gz"
      sha256 "4841bf72282cab15bb76369f58f677537658f056e7bbf0fb5708c8cf0b684fd4"

      def install
        bin.install "bytehouse-cli"
        man1.install Dir["manual/bytehouse-cli.1"]
      end
    end
  end

  def caveats; <<~EOS
    Bytehouse SQL Gateway Command Line Interface to interact with cnch via gateway
  EOS
  end

  test do
    system "#{bin}/bytehouse-cli", "--version"
  end
end
